### ISSUE TITLE
可以出个详细些的部署到自己服务器上的教程吗？

### ISSUE THREAD

**Issue by meetcode** [chairc/wps-invite#5]
你好，部署到自己服务器上的教程看不太懂，麻烦可以出个详细点的部署教程吗，谢谢。

**Comment by chairc** [comment]
请问你是想要部署全教程吗，如果是部署全教程的话直接按照SpringBoot部署方式使用。

**Comment by chairc** [comment]
> 你好，部署到自己服务器上的教程看不太懂，麻烦可以出个详细点的部署教程吗，谢谢。

请问你是想要部署全教程吗，如果是部署全教程的话直接按照SpringBoot部署方式使用。

**Comment by meetcode** [comment]
SpringBoot部署是怎么样操作？

**Comment by chairc** [comment]
> SpringBoot部署是怎么样操作？

1. 用Git命令或者压缩包先把项目下载下来，解压文件，使用idea打开项目
2. 对项目的application-dev.yml进行配置，修改url、username、password、driver-class-name
3. 数据库文件在sql文件夹里，将他在Navicat中运行
4. 运行项目，在网页中输入localhost:8080即可
